### ISSUE TITLE
🧑‍🔬 Add docc documentation

### ISSUE THREAD

**Issue by superturboryan** [superturboryan/ControlKit#5]
The package's `docc` documentation can be hosted and viewed on the **Swift Package Index**, see [hosting your documentation](https://swiftpackageindex.com/SwiftPackageIndex/SPIManifest/~/documentation/spimanifest/commonusecases#spiHosting) in the Swift Package Index documentation.

This should involve adding a `Swift Package Index` file:  

```yml
# .spi.yml

version: 1
builder:
  configs:
    - documentation_targets: [Target1, Target2]
      platform: ios
```

- Check out [Apple's **SlothCreator**](https://developer.apple.com/documentation/xcode/slothcreator_building_docc_documentation_in_xcode) example package for examples of `docc` formatting.
- [Xcode / Writing Documentation](https://developer.apple.com/documentation/xcode/writing-documentation)
